#!/usr/bin/env python3
#a simple CLI interface for the auto physics experiment tool kits
#by ustcpetergu

import sys
import os
import getopt
from ftplib import FTP
import getpass

def usage():
    print('read the source code yourself to get help')
def wrong():
    print('something went wrong...')
def initnew():
    print('init done.')
    pass
def upload(filename):
    #upload to qingmiyunyin print system, TODO
    pass

if __name__ == '__main__':
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hi:u:", ["help", "init=", "upload="])
    except getopt.GetoptError as err:
        print(err)
        usage()
        sys.exit(2)
    if args != []:
        print('unhandled argument detected.')
        sys.exit(3)
    for o, a in opts:
        if o in ("-h", "--help"):
            usage()
            sys.exit()
        elif o in ("-i", "--init"):
            initnew()
            sys.exit()
        elif o in ("-u", "--upload"):
            upload(a)
            sys.exit()
        else:
            wrong()
            sys.exit(2)

